"use client";
import { useEffect, useState } from "react";
import { ClipboardCheck, Clock3, LoaderCircle, ScanBarcode, Search, X } from "lucide-react";
import type { getUsageSession, listMyUsageSessions } from "@/lib/usage-db";
import type { ViewId } from "./modules";
import { useAuth } from "./auth-provider";
import { formatDate, formatNumber } from "./report-state";
import { resultLabels } from "@/lib/report-data";
type MySession = Awaited<ReturnType<typeof listMyUsageSessions>>[number];
type MyDetail = NonNullable<Awaited<ReturnType<typeof getUsageSession>>>;

export default function MyUsageView({ onNavigate }: { onNavigate: (view: ViewId, sessionId?: string) => void }) {
  const { user } = useAuth();
  const [sessions,setSessions] = useState<MySession[]>([]), [loading,setLoading] = useState(true), [error,setError] = useState(""), [query,setQuery] = useState(""), [filter,setFilter] = useState("ALL"), [revision,setRevision] = useState(0);
  const [detail,setDetail] = useState<MyDetail | null>(null), [opening,setOpening] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); fetch("/api/v1/my-usage", { cache:"no-store", signal:controller.signal }).then(async response => { const body=await response.json(); if(!response.ok) throw new Error(body.message); setSessions(body.sessions); setError(""); }).catch(failure => { if(!controller.signal.aborted) setError(failure.message); }).finally(() => { if(!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [revision]);
  const active = sessions.filter(session => session.status === "ACTIVE");
  const visible = sessions.filter(session => (filter === "ALL" || session.status === filter) && `${session.number} ${session.activityName}`.toLowerCase().includes(query.toLowerCase()));
  const openDetail = async (id: string) => { setOpening(id); try { const response = await fetch(`/api/v1/usages/${id}`, { cache:"no-store" }); const body=await response.json(); if(!response.ok) throw new Error(body.message); setDetail(body.session); } catch(failure) { setError(failure instanceof Error ? failure.message : "Detail belum dapat dimuat."); } finally { setOpening(null); } };
  return <div className="accounts-view"><div className="module-heading"><div><span className="eyebrow">PENGGUNAAN SAYA</span><h1>Halo, {user?.name}</h1><p>Ambil filamen dan selesaikan penggunaan Anda di sini.</p></div><button className="button primary" onClick={() => onNavigate("usage-start")}><ScanBarcode size={19} /> Mulai penggunaan / Scan</button></div>
    <div className="my-usage-stats"><article><Clock3 size={22} /><div><span>Penggunaan aktif</span><strong>{loading ? "—" : active.length}</strong></div></article><article><ClipboardCheck size={22} /><div><span>Penggunaan selesai</span><strong>{loading ? "—" : sessions.filter(session=>session.status === "COMPLETED").length}</strong></div></article><article><ScanBarcode size={22} /><div><span>Total gram terpakai</span><strong>{loading ? "—" : `${formatNumber(sessions.filter(session=>session.status === "COMPLETED").reduce((sum,session)=>sum+session.totalUsedGrams,0))} g`}</strong></div></article></div>
    {active.length ? <div className="my-usage-reminder"><Clock3 size={20} /><p>Ada <strong>{active.length} penggunaan</strong> yang belum diselesaikan. Catat gram terpakai setelah pekerjaan selesai.</p></div> : null}
    {error ? <div className="inventory-form-error" role="alert">{error}<button className="button secondary" onClick={()=>setRevision(value=>value+1)}>Muat ulang</button></div> : null}
    <section className="data-panel"><div className="toolbar"><label className="table-search"><Search size={17} /><input aria-label="Cari penggunaan saya" placeholder="Cari nomor atau nama kegiatan..." value={query} onChange={event=>setQuery(event.target.value)} /></label><select className="role-select account-filter" aria-label="Status penggunaan" value={filter} onChange={event=>setFilter(event.target.value)}><option value="ALL">Semua penggunaan</option><option value="ACTIVE">Aktif</option><option value="COMPLETED">Selesai</option></select></div><div className="table-wrap" tabIndex={0} role="region" aria-label="Tabel penggunaan saya"><table className="data-table account-table"><thead><tr><th>Penggunaan</th><th>Mulai (WIB)</th><th>Unit</th><th>Status</th><th>Terpakai</th><th>Aksi</th></tr></thead><tbody>{loading ? <tr><td colSpan={6}><LoaderCircle className="spin" size={20} /> Memuat penggunaan...</td></tr> : visible.map(session=><tr key={session.id}><td><strong>{session.number}</strong><small>{session.activityName || (session.usageType === "CLASS" ? "Kelas" : "Nonkelas")}</small></td><td>{formatDate(session.startedAt)}</td><td>{session.unitCount}</td><td><span className={`status ${session.status === "ACTIVE" ? "info" : "success"}`}><i />{session.status === "ACTIVE" ? "Aktif" : "Selesai"}</span></td><td>{session.status === "ACTIVE" ? "Belum selesai" : `${formatNumber(session.totalUsedGrams)} g`}</td><td><div className="row-actions"><button className="mini-button" disabled={Boolean(opening)} onClick={()=>void openDetail(session.id)}>{opening === session.id ? <LoaderCircle className="spin" size={15} /> : null} Detail</button>{session.status === "ACTIVE" ? <button className="mini-button" onClick={()=>onNavigate("usage-complete",session.id)}>Selesaikan</button> : null}</div></td></tr>)}{!loading && !visible.length ? <tr><td colSpan={6}><div className="report-empty">Belum ada penggunaan yang sesuai.</div></td></tr> : null}</tbody></table></div></section>
    {detail ? <section className="form-panel my-usage-detail"><div className="section-title"><div><h2>{detail.number}</h2><p>{detail.activityName || "Detail penggunaan"}</p></div><button className="icon-button" aria-label="Tutup detail" onClick={()=>setDetail(null)}><X size={20} /></button></div><p>Pengambil: <strong>{detail.userName}</strong> · Dicatat oleh: <strong>{detail.createdByName || "Tidak tercatat"}</strong></p><p>{formatDate(detail.startedAt)} → {detail.completedAt ? formatDate(detail.completedAt) : "Masih digunakan"}</p><div className="table-wrap" tabIndex={0} role="region" aria-label="Rincian filamen"><table className="data-table"><thead><tr><th>Filamen / barcode</th><th>Gram awal</th><th>Terpakai</th><th>Sisa setelah sesi</th></tr></thead><tbody>{detail.items.map(item=><tr key={item.inventoryItemId}><td><strong>{item.product} · {item.color}</strong><small>{item.code}</small></td><td>{formatNumber(item.startingGrams)} g</td><td>{item.usedGrams === null ? "—" : `${formatNumber(item.usedGrams)} g`}</td><td>{item.returnedGrams === null ? "—" : `${formatNumber(item.returnedGrams)} g`}</td></tr>)}</tbody></table></div><p>Hasil: {detail.result ? resultLabels[detail.result] : "Belum selesai"}</p><p>{detail.notes || "Tidak ada catatan."}</p>{detail.completedByName ? <p>Diselesaikan oleh: {detail.completedByName}</p> : null}</section> : null}
  </div>;
}
